### ISSUE TITLE
Simplify CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [aarondukepifanio/prj-rev-bwfs-dasmoto#5]
It is best to try to simplify the CSS code as much as possible for shared properties. There are a few shared properties among elements that can be simplified like so,

```css
h1, h2, .sale {
  font-family: Helvetica;
  font-weight: bold;
}

h2 {
  font-size: 32px;
  color: white;
}
```
